name: CI

on:
  push:
    paths:
      - "**.zz"
      - "src/**"
      - "test/zz/**"
      - "include/**"
      - "main.cpp"
      - "*.yml"
      - "**.py"
      - "CMakeLists.txt"
  pull_request: {}

jobs:
  test-linux-llvm:
    runs-on: ubuntu-latest
    env:
      TARGET: linux,llvm
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential llvm clang cmake python3-pip
      - name: Build zpiler
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j
          sudo cp zpiler /usr/local/bin/
      - name: Run Tests
        run: python3 test_runner.py

  test-windows:
    runs-on: windows-latest
    env:
      TARGET: windows
    steps:
      - uses: actions/checkout@v3

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake
        run: choco install --no-progress -y cmake

      - name: Build zpiler
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release
          nmake
          copy zpiler.exe %USERPROFILE%\zpiler.exe

      - name: Add to PATH
        shell: cmd
        run: |
          set ZPILER_PATH=%USERPROFILE%\\zpiler.exe
          set PATH=%USERPROFILE%;%PATH%

      - name: Run Tests
        shell: cmd
        run: python test_runner.py --zpiler-path "%ZPILER_PATH%"
