name: CI

on:
  push:
    paths:
      - "**.zz"
      - "src/**"
      - "test/zz/**"
  pull_request: {}

jobs:
  test-linux-llvm:
    runs-on: ubuntu-latest
    env:
      TARGET: linux,llvm
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential llvm clang cmake python3-pip
      - name: Build zpiler
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j
          sudo cp zpiler /usr/local/bin/
      - name: Run Tests
        run: python3 test_runner.py

  test-windows:
    runs-on: windows-latest
    env:
      # Only run the windows target
      TARGET: windows
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSVC
        shell: pwsh
        run: |
          & "${Env:ProgramFiles(x86)}\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat"
      - name: Install CMake
        shell: pwsh
        run: choco install --no-progress -y cmake
      - name: Build zpiler
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          copy .\\Release\\zpiler.exe $Env:USERPROFILE\\zpiler.exe
          setx PATH \"$Env:USERPROFILE;$Env:PATH\"
      - name: Run Tests
        shell: pwsh
        run: python test_runner.py
